packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@sanchika/tokens@0.1.1": "https://github.com/lamemustafa/sanchika/releases/download/v0.1.1/sanchika-tokens-0.1.1.tgz"
  "@sanchika/primitives@0.1.1": "https://github.com/lamemustafa/sanchika/releases/download/v0.1.1/sanchika-primitives-0.1.1.tgz"

catalog:
  "@astrojs/check": "0.9.9"
  astro: "7.1.1"
  typescript: "7.0.2"
