packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@sanchika/tokens@0.1.0": "https://github.com/lamemustafa/sanchika/releases/download/v0.1.0/sanchika-tokens-0.1.0.tgz"
  "@sanchika/primitives@0.1.0": "https://github.com/lamemustafa/sanchika/releases/download/v0.1.0/sanchika-primitives-0.1.0.tgz"

catalog:
  "@astrojs/check": "0.9.9"
  astro: "7.0.9"
  typescript: "6.0.3"
